// ============================================================
// THE SACRED HEARTS — PRODUCT CATALOG
// ============================================================
// To add, edit, or remove products, update this file.
// Each product needs: id, name, cat, price, startPrice,
// img, desc, sale, and optionally outOfStock or isFree.
// ============================================================

export interface Product {
  id: number;
  name: string;
  cat: string;
  price: string;
  startPrice: number;
  img: string;
  desc: string;
  sale: boolean;
  outOfStock?: boolean;
  isFree?: boolean;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Sacred Heart of Jesus – Classic Plaques (English)",
    cat: "Plaques",
    price: "$73.00 – $310.00",
    startPrice: 73,
    img: "https://thesacredhearts.org/wp-content/uploads/2020/01/1-SHJ-300x300.jpg",
    desc: "Our most beloved plaque featuring the Sacred Heart of Jesus with the 12 Promises printed in English. Beautifully crafted and available in multiple sizes. A treasured addition to any home or parish. Free Shipping.",
    sale: true,
  },
  {
    id: 2,
    name: "Immaculate Heart of Mary – Classic Plaques (English)",
    cat: "Immaculate Heart of Mary",
    price: "$73.00 – $310.00",
    startPrice: 73,
    img: "https://thesacredhearts.org/wp-content/uploads/2020/01/1-IHM-300x300.jpg",
    desc: "A beautiful plaque of the Immaculate Heart of Mary with promises printed in English. Available in multiple sizes. Perfect companion to the Sacred Heart plaque. Free Shipping.",
    sale: true,
  },
  {
    id: 3,
    name: "First Holy Communion – Jesus with Children",
    cat: "First Holy Communion",
    price: "$54.00 – $160.00",
    startPrice: 54,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5452-1-300x300.jpg",
    desc: "A touching image of Jesus with children, perfect for commemorating a child's First Holy Communion. A lasting keepsake to mark this important sacrament. Free Shipping.",
    sale: true,
  },
  {
    id: 4,
    name: "Immaculate Heart of Mary, C",
    cat: "Immaculate Heart of Mary",
    price: "$25.00 – $150.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5439-1-300x300.jpg",
    desc: "A beautiful devotional print of the Immaculate Heart of Mary. Available in multiple sizes to suit any space — from personal prayer corners to parish display. Free Shipping.",
    sale: true,
  },
  {
    id: 5,
    name: "Baptismal / Angel of God Plaque",
    cat: "Plaques",
    price: "$54.00 – $160.00",
    startPrice: 54,
    img: "https://thesacredhearts.org/wp-content/uploads/2023/02/IMG_6631-2-300x300.jpg",
    desc: "A lovely plaque featuring the Angel of God prayer, perfect for baptisms, nurseries, and children's rooms. A beautiful and meaningful baptism gift. Free Shipping.",
    sale: true,
  },
  {
    id: 6,
    name: "Combo Pack – Classic Plaques (Spanish)",
    cat: "Plaques",
    price: "$85.00 – $620.00",
    startPrice: 85,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/SHJ-IHM2-1-300x300.png",
    desc: "A combo pack featuring both the Sacred Heart of Jesus and Immaculate Heart of Mary classic plaques with promises printed in Spanish. Ideal for Spanish-speaking families and parishes. Free Shipping.",
    sale: true,
  },
  {
    id: 7,
    name: "First Holy Communion – Jesus with Gold Border",
    cat: "First Holy Communion",
    price: "$54.00 – $160.00",
    startPrice: 54,
    img: "https://thesacredhearts.org/wp-content/uploads/2023/10/IMG_05232-300x300.jpg",
    desc: "An elegant First Holy Communion image of Jesus with a beautiful gold border. A refined and memorable keepsake for this sacred milestone. Free Shipping.",
    sale: true,
  },
  {
    id: 8,
    name: "Immaculate Heart of Mary – Classic Plaques (Spanish)",
    cat: "Immaculate Heart of Mary",
    price: "$73.00 – $310.00",
    startPrice: 73,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5459-1-300x300.jpg",
    desc: "The classic Immaculate Heart of Mary plaque with promises printed in Spanish. Available in multiple sizes for homes and parishes. Free Shipping.",
    sale: true,
  },
  {
    id: 9,
    name: "Immaculate Heart of Mary, 8 in. × 8 in.",
    cat: "Immaculate Heart of Mary",
    price: "$31.00 – $126.00",
    startPrice: 31,
    img: "https://thesacredhearts.org/wp-content/uploads/2026/03/IMG_3804-1-300x300.jpg",
    desc: "A stunning 8×8 inch tile of the Immaculate Heart of Mary. Beautiful in any home, chapel, or prayer space.",
    sale: true,
  },
  {
    id: 10,
    name: "Picture Stands – 6 in., 8 in., or 10 in.",
    cat: "Accessories",
    price: "$23.00 – $56.00",
    startPrice: 23,
    img: "https://thesacredhearts.org/wp-content/uploads/2026/03/IMG_3561-300x300.jpg",
    desc: "Display stands available in three sizes (6\", 8\", and 10\") to showcase your sacred prints and tiles with dignity and beauty.",
    sale: true,
  },
  {
    id: 11,
    name: "Sacred Heart Badges",
    cat: "Miscellaneous",
    price: "$20.00 – $80.00",
    startPrice: 20,
    img: "https://thesacredhearts.org/wp-content/uploads/woocommerce-placeholder.png",
    desc: "Sacred Heart badges for personal devotion, distribution, or parish use. Available in bulk quantities. A simple and powerful way to spread devotion. Free Shipping.",
    sale: true,
  },
  {
    id: 12,
    name: "Sacred Heart of Jesus – Classic Plaques (Spanish)",
    cat: "Plaques",
    price: "$73.00 – $310.00",
    startPrice: 73,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5462-1-300x300.jpg",
    desc: "The classic Sacred Heart of Jesus plaque with promises printed in Spanish. Available in multiple sizes for homes and parishes. Free Shipping.",
    sale: true,
  },
  {
    id: 13,
    name: "St. Carlo Acutis, 8 in. × 8 in.",
    cat: "Saints",
    price: "$31.00 – $126.00",
    startPrice: 31,
    img: "https://thesacredhearts.org/wp-content/uploads/2026/03/IMG_3805-300x300.jpg",
    desc: "A beautiful 8×8 inch tile of Blessed Carlo Acutis, patron of the internet and inspiring model of holiness for young Catholics.",
    sale: true,
  },
  {
    id: 14,
    name: "St. Joseph, Terror of Demons, 8 in. × 10 in.",
    cat: "Saints",
    price: "$41.00 – $64.00",
    startPrice: 41,
    img: "https://thesacredhearts.org/wp-content/uploads/2026/04/IMG_3825-300x300.jpg",
    desc: "A powerful image of St. Joseph, Terror of Demons — a timely and beautiful devotional image for every Catholic home and family.",
    sale: true,
  },
  {
    id: 15,
    name: "The Heart of Jesus (Cor Salvatoris), 6×8 in.",
    cat: "Sacred Heart of Jesus",
    price: "$31.00 – $136.00",
    startPrice: 31,
    img: "https://thesacredhearts.org/wp-content/uploads/2026/03/IMG_3793-300x300.jpg",
    desc: "The Heart of Jesus — Cor Salvatoris — in a beautiful 6×8 inch format. A treasured devotional image for prayer and contemplation.",
    sale: true,
  },
  {
    id: 16,
    name: "The Immaculate Heart of Mary, 6 in. × 8 in.",
    cat: "Immaculate Heart of Mary",
    price: "$31.00 – $136.00",
    startPrice: 31,
    img: "https://thesacredhearts.org/wp-content/uploads/2026/03/IMG_3795-300x300.jpg",
    desc: "The Immaculate Heart of Mary in a beautiful 6×8 inch format. Perfect for the home, office, or chapel.",
    sale: true,
  },
  {
    id: 17,
    name: "The Sacred Heart of Jesus (Cor Salvatoris), 8×8 in.",
    cat: "Sacred Heart of Jesus",
    price: "$31.00 – $126.00",
    startPrice: 31,
    img: "https://thesacredhearts.org/wp-content/uploads/2026/03/IMG_3803-300x300.jpg",
    desc: "The Sacred Heart of Jesus — Cor Salvatoris — in an elegant 8×8 inch tile format. A beautiful devotional centerpiece.",
    sale: true,
  },
  {
    id: 18,
    name: "Sacred Heart of Jesus (Classic Print)",
    cat: "Sacred Heart of Jesus",
    price: "$40.00 – $150.00",
    startPrice: 40,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5449-1-300x300.jpg",
    desc: "The classic devotional print of the Sacred Heart of Jesus. Available in multiple sizes. A timeless image for any home. Free Shipping.",
    sale: true,
  },
  {
    id: 19,
    name: "Immaculate Heart of Mary (Classic Print)",
    cat: "Immaculate Heart of Mary",
    price: "$40.00 – $150.00",
    startPrice: 40,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5448-1-300x300.jpg",
    desc: "The classic devotional print of the Immaculate Heart of Mary. Available in multiple sizes. Free Shipping.",
    sale: true,
  },
  {
    id: 20,
    name: "Combo Pack – Classic Plaques (English)",
    cat: "Plaques",
    price: "$85.00 – $620.00",
    startPrice: 85,
    img: "https://thesacredhearts.org/wp-content/uploads/2018/10/SHJandIHM57-300x300.jpg",
    desc: "Both the Sacred Heart of Jesus and Immaculate Heart of Mary classic plaques with promises in English. The perfect set for your home Enthronement. Free Shipping.",
    sale: true,
  },
  {
    id: 21,
    name: "First Holy Communion Remembrance",
    cat: "First Holy Communion",
    price: "$40.00 – $100.00",
    startPrice: 40,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5469-1-300x300.jpg",
    desc: "A beautiful remembrance print for a child's First Holy Communion. A lasting keepsake to treasure for years to come. Free Shipping.",
    sale: true,
  },
  {
    id: 22,
    name: "Last Supper",
    cat: "Miscellaneous",
    price: "$45.00 – $150.00",
    startPrice: 45,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_4397-3-300x300.jpg",
    desc: "A timeless image of the Last Supper, ideal for dining rooms, kitchens, and family gathering spaces. Free Shipping.",
    sale: true,
  },
  {
    id: 23,
    name: "Sacred Heart of Jesus, D",
    cat: "Sacred Heart of Jesus",
    price: "$25.00 – $150.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5428-1-300x300.jpg",
    desc: "A beautiful devotional print of the Sacred Heart of Jesus. Available in multiple sizes. Free Shipping.",
    sale: true,
  },
  {
    id: 24,
    name: "Sacred Heart of Jesus, E",
    cat: "Sacred Heart of Jesus",
    price: "$25.00 – $150.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5484-1-300x300.jpg",
    desc: "A beloved image of the Sacred Heart of Jesus in a classic devotional style. Available in multiple sizes. Free Shipping.",
    sale: true,
  },
  {
    id: 25,
    name: "Sacred Heart of Jesus, G",
    cat: "Sacred Heart of Jesus",
    price: "$25.00 – $80.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5442-1-300x300.jpg",
    desc: "A beautiful Sacred Heart of Jesus print available in multiple sizes. Free Shipping.",
    sale: true,
  },
  {
    id: 26,
    name: "'Thy Kingdom Come' Booklet",
    cat: "Booklets",
    price: "$4.00",
    startPrice: 4,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_4428-2-300x300.jpg",
    desc: "A devotional booklet on the Enthronement and the Reign of Christ. Free Shipping.",
    sale: false,
    outOfStock: true,
  },
  {
    id: 27,
    name: "Enthronement Booklet",
    cat: "Booklets",
    price: "$15.00",
    startPrice: 15,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_4426-2-300x300.jpg",
    desc: "A complete guide to the Enthronement of the Sacred Heart in the home. A beautiful and essential resource for families. Free Shipping.",
    sale: false,
  },
  {
    id: 28,
    name: "Guardian Angel Prayer",
    cat: "Miscellaneous",
    price: "$25.00 – $80.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5435-1-300x300.jpg",
    desc: "A beautiful print of the Guardian Angel Prayer, beloved for children's rooms, nurseries, and school classrooms. Free Shipping.",
    sale: true,
  },
  {
    id: 29,
    name: "Irish Blessing",
    cat: "Miscellaneous",
    price: "$25.00 – $80.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5488-1-300x300.jpg",
    desc: "The timeless Irish Blessing — a thoughtful and beautiful gift for any occasion. Free Shipping.",
    sale: true,
  },
  {
    id: 30,
    name: "Mary with Child Jesus, A",
    cat: "Marian",
    price: "$25.00 – $80.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_4395-2-300x300.jpg",
    desc: "A tender and beautiful image of Our Lady with the Child Jesus. Perfect for any Marian devotion space. Free Shipping.",
    sale: true,
  },
  {
    id: 31,
    name: "Mary with Child Jesus, B",
    cat: "Marian",
    price: "$25.00 – $80.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5562-1-300x300.jpg",
    desc: "A second beautiful version of Our Lady with the Child Jesus. Free Shipping.",
    sale: true,
  },
  {
    id: 32,
    name: "Mary with Child Jesus, C",
    cat: "Marian",
    price: "$25.00 – $80.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_4402-2-300x300.jpg",
    desc: "A third graceful image of Our Lady with the Child Jesus. Free Shipping.",
    sale: true,
  },
  {
    id: 33,
    name: "Parish Display",
    cat: "Display",
    price: "Free",
    startPrice: 0,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/display-box-3-300x300.jpg",
    desc: "A display box for parish use to share Sacred Hearts images with parishioners. Contact us to request your free parish display.",
    sale: true,
    isFree: true,
  },
  {
    id: 34,
    name: "Sacred Heart of Jesus, B",
    cat: "Sacred Heart of Jesus",
    price: "$40.00 – $150.00",
    startPrice: 40,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5444-1-300x300.jpg",
    desc: "A beautiful classic print of the Sacred Heart of Jesus. Available in multiple sizes. Free Shipping.",
    sale: true,
  },
  {
    id: 35,
    name: "Sacred Heart of Jesus, C",
    cat: "Sacred Heart of Jesus",
    price: "$25.00 – $150.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5438-1-300x300.jpg",
    desc: "A devotional print of the Sacred Heart of Jesus. Available in multiple sizes. Free Shipping.",
    sale: true,
  },
  {
    id: 36,
    name: "Sacred Heart of Jesus, F",
    cat: "Sacred Heart of Jesus",
    price: "$25.00 – $80.00",
    startPrice: 25,
    img: "https://thesacredhearts.org/wp-content/uploads/2020/01/8-SHJ-300x300.jpg",
    desc: "A beloved image of the Sacred Heart of Jesus in multiple sizes. Free Shipping.",
    sale: true,
  },
  {
    id: 37,
    name: "First Holy Communion – Jesus with Young Boy",
    cat: "First Holy Communion",
    price: "$54.00 – $160.00",
    startPrice: 54,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5455-1-300x300.jpg",
    desc: "A touching image of Jesus with a young boy, perfect for a boy's First Holy Communion. Free Shipping.",
    sale: true,
  },
  {
    id: 38,
    name: "First Holy Communion – Jesus with Young Girl",
    cat: "First Holy Communion",
    price: "$54.00 – $160.00",
    startPrice: 54,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5454-1-300x300.jpg",
    desc: "A tender image of Jesus with a young girl, perfect for a girl's First Holy Communion. Free Shipping.",
    sale: true,
  },
  {
    id: 39,
    name: "Immaculate Heart of Mary, B",
    cat: "Immaculate Heart of Mary",
    price: "$35.00 – $150.00",
    startPrice: 35,
    img: "https://thesacredhearts.org/wp-content/uploads/2021/02/IMG_5445-1-300x300.jpg",
    desc: "A second beautiful version of the Immaculate Heart of Mary devotional print. Available in multiple sizes. Free Shipping.",
    sale: true,
  },
];

export const FEATURED_IDS = [1, 2, 3, 4, 22, 27];

export const CATEGORIES = [
  "All",
  ...Array.from(new Set(PRODUCTS.map((p) => p.cat))),
];
